import setuptools

with open("README.md", "r", encoding = "utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    name = "autobanner",
    version = "0.0.1",
    author = "asj",
    author_email = "andrewstanfordjason@gmail.com",
    description = "Automatic banners for autogenerated files",
    long_description = long_description,
    long_description_content_type = "text/markdown",
    url = "https://github.com/andrewstanfordjason/autobanner",
    license_files = ('LICENSE'),
    classifiers = [
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    package_dir = {"": "src"},
    packages = setuptools.find_packages(where="src"),
    python_requires = ">=3.6"
)